# Generated by Django 2.1.5 on 2019-01-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creditcardexpirationdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
