# Generated by Django 2.1.5 on 2019-01-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_creditcardexpirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creditcardtype',
            field=models.CharField(blank=True, choices=[('V', 'Visa'), ('M', 'Mastercard'), ('A', 'American Express')], max_length=1, null=True),
        ),
    ]
