# Generated by Django 2.1.5 on 2019-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_creditcardtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationstable',
            fields=[
                ('lon', models.DecimalField(blank=True, decimal_places=16, max_digits=30, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('num_bikes_available', models.IntegerField(blank=True, null=True)),
                ('last_reported', models.IntegerField(blank=True, null=True)),
                ('is_installed', models.TextField(blank=True, null=True)),
                ('num_docks_available', models.IntegerField(blank=True, null=True)),
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_renting', models.TextField(blank=True, null=True)),
                ('is_returning', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'stationstable',
                'managed': False,
            },
        ),
    ]
