# Generated by Django 2.1.5 on 2019-01-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_stationstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('rack_capacity', models.IntegerField()),
                ('num_racks_available', models.IntegerField()),
                ('info', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('lon', models.DecimalField(decimal_places=16, max_digits=30)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=30)),
                ('is_active', models.IntegerField()),
                ('image', models.CharField(max_length=30)),
                ('fine_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('fine_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
    ]
