# Generated by Django 2.1.5 on 2019-01-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bike_biketype'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfBike',
            fields=[
                ('bike_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_status_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'status_of_bike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfBike',
            fields=[
                ('bike_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_info', models.CharField(max_length=100)),
                ('bike_model', models.CharField(max_length=20)),
                ('bike_type', models.CharField(max_length=20)),
                ('bike_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('bike_image', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'type_of_bike',
                'managed': False,
            },
        ),
    ]
