# Generated by Django 2.1.5 on 2019-01-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_statusofbike_typeofbike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statusofbike',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typeofbike',
            options={},
        ),
    ]
