# Generated by Django 2.1.5 on 2019-03-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190302_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'managed': False},
        ),
    ]
