# Generated by Django 2.1.5 on 2019-03-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190309_1208'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='contactUs',
        ),
    ]
